import os


DEFAULT_DEPLOYMENT_CALLIBRI = "callibri-loader-clickhouse/callibri-loader-clickhouse"

PREFECT_DEPLOYMENT_CALLIBRI = os.getenv(
    "PREFECT_DEPLOYMENT_CALLIBRI",
    DEFAULT_DEPLOYMENT_CALLIBRI,
)
PREFECT_DEPLOYMENT_CALLIBRI_SINGLE = os.getenv(
    "PREFECT_DEPLOYMENT_CALLIBRI_SINGLE",
    PREFECT_DEPLOYMENT_CALLIBRI,
)
