import os


DEFAULT_DEPLOYMENT_CALLTOUCH = "calltouch-loader-clickhouse/calltouch-loader-clickhouse"

PREFECT_DEPLOYMENT_CALLTOUCH = os.getenv(
    "PREFECT_DEPLOYMENT_CALLTOUCH",
    DEFAULT_DEPLOYMENT_CALLTOUCH,
)
PREFECT_DEPLOYMENT_CALLTOUCH_SINGLE = os.getenv(
    "PREFECT_DEPLOYMENT_CALLTOUCH_SINGLE",
    PREFECT_DEPLOYMENT_CALLTOUCH,
)
