import os


DEFAULT_DEPLOYMENT_ROISTAT = "roistat-loader-clickhouse/roistat-loader-clickhouse"

PREFECT_DEPLOYMENT_ROISTAT = os.getenv(
    "PREFECT_DEPLOYMENT_ROISTAT",
    DEFAULT_DEPLOYMENT_ROISTAT,
)
PREFECT_DEPLOYMENT_ROISTAT_SINGLE = os.getenv(
    "PREFECT_DEPLOYMENT_ROISTAT_SINGLE",
    PREFECT_DEPLOYMENT_ROISTAT,
)
