import os


DEFAULT_DEPLOYMENT_DIRECT_ANALYTICS = "direct-loader-clickhouse/direct-analytics-change"
DEFAULT_DEPLOYMENT_DIRECT_LIGHT = "direct-loader-clickhouse/direct-light-hourly"

PREFECT_DEPLOYMENT_DIRECT_ALL = os.getenv(
    "PREFECT_DEPLOYMENT_DIRECT_ALL",
    DEFAULT_DEPLOYMENT_DIRECT_ANALYTICS,
)
PREFECT_DEPLOYMENT_DIRECT_SINGLE = os.getenv(
    "PREFECT_DEPLOYMENT_DIRECT_SINGLE",
    "",
)
PREFECT_DEPLOYMENT_DIRECT_SINGLE_ANALYTICS = os.getenv(
    "PREFECT_DEPLOYMENT_DIRECT_SINGLE_ANALYTICS",
    PREFECT_DEPLOYMENT_DIRECT_SINGLE or DEFAULT_DEPLOYMENT_DIRECT_ANALYTICS,
)
PREFECT_DEPLOYMENT_DIRECT_SINGLE_LIGHT = os.getenv(
    "PREFECT_DEPLOYMENT_DIRECT_SINGLE_LIGHT",
    PREFECT_DEPLOYMENT_DIRECT_SINGLE or DEFAULT_DEPLOYMENT_DIRECT_LIGHT,
)
PREFECT_DEPLOYMENT_DIRECT_ANALYTICS = os.getenv(
    "PREFECT_DEPLOYMENT_DIRECT_ANALYTICS",
    DEFAULT_DEPLOYMENT_DIRECT_ANALYTICS,
)
PREFECT_DEPLOYMENT_DIRECT_LIGHT = os.getenv(
    "PREFECT_DEPLOYMENT_DIRECT_LIGHT",
    DEFAULT_DEPLOYMENT_DIRECT_LIGHT,
)
