import os


DEFAULT_DEPLOYMENT_METRIKA = "metrika-loader-clickhouse/metrika-loader-clickhouse"

PREFECT_DEPLOYMENT_METRIKA_ALL = os.getenv(
    "PREFECT_DEPLOYMENT_METRIKA_ALL",
    DEFAULT_DEPLOYMENT_METRIKA,
)
PREFECT_DEPLOYMENT_METRIKA_SINGLE = os.getenv(
    "PREFECT_DEPLOYMENT_METRIKA_SINGLE",
    PREFECT_DEPLOYMENT_METRIKA_ALL,
)
